### PR TITLE
Addon compatibility check for bundles

### PR DESCRIPTION
**Pull request by martastain**
https://github.com/ynput/ayon-backend/issues/123

## Testing
- Create an addon with dependencies (as described in the linked issue)
- Try creating a bundle that does not meet the dependencies
- It should display an error

When the frontend counterpart of this PR is completed, the frontend will display errors and warnings inline.

### CODE REVIEW

**Comment by martastain** [comment]
During bundle creation (when user edits the form), the frontend may call an endpoint with the same payload it would send for the actual create, but it would return sanity check result which may be displayed inline (and disable save button when checks fail).

image

**Comment by martastain** [comment]
image

**Comment by iLLiCiTiT** [comment]
> @iLLiCiTiT do you think create bundle endpoint should fail when there's an error or should i just disable the save option in the UI?

My personal opinion is that it should.

Does the information returned from server also report which addon caused the issue? E.g. `sitesync` is not installed, but who requested it?

**Comment by martastain** [comment]
> Does the information returned from server also report what caused the issue? E.g. `sitesync` is not installed, but what requested it?

Yes. It is pretty granular. In this case (screenshot), sitesync is not requested by any of the addon, but it failed to start, hence this message - it references itself. (but it shouldn't be possible to select it at all). And every addon can return multiple issues.

**Comment by martastain** [comment]
> > @iLLiCiTiT do you think create bundle endpoint should fail when there's an error or should i just disable the save option in the UI?
> 
> My personal opinion is that it should.

Sorry, but "it should" is quite ambiguous in this case :)

**Comment by martastain** [comment]
I think that check could be performed by default and prevent creation if it fails, but we can have `force=true` argument to override if needed. That would be consistent with other use of `force` flag across the API

**Comment by jakubjezek001** [comment]
I would like to test it, but the descriptions are missing some testing steps. Could we add those please, it will improve the review-ability?

**Comment by martastain** [comment]
> I think that check could be performed by default and prevent creation if it fails, but we can have `force=true` argument to override if needed. That would be consistent with other use of `force` flag across the API

image

**Comment by iLLiCiTiT** [comment]
> I think that check could be performed by default and prevent creation if it fails, but we can have force=true argument to override if needed. That would be consistent with other use of force flag across the API

I think we might need the force for dev bundles.

**Comment by martastain** [comment]
> I think we might need the force for dev bundles.

Yep. That makes sense... I'll do that in https://github.com/ynput/ayon-frontend/pull/369

**Comment by antirotor** [comment]
... and just to add to the bitching (but otherwise I  think the code looks solid) - it is missing PR in https://github.com/ynput/ayon-tests

**Comment by iLLiCiTiT** [comment]
Works. We should add it to example addon and make nice frontend 🙂

**Comment by iLLiCiTiT** [comment]
And maybe define example version ranges that are supported? E.g. `">=1.0.0,<1.1.0"` would work?

**Comment by Innders** [comment]
```python
ayon_compatible_addons = {
    "tvpaint": "<=0.1.0",
}
```

```json
[
  {
    "severity": "warning",
    "addon": "webpublisher",
    "message": "tvpaint <=0.1.0 is required"
  }
]
```

Maybe the wording "required" should be slightly different here as this is a warning about compatibility not requirements.

Suggestion: `Webpublisher is only compatible with TVPaint <=0.1.0`

Even better would be human readable version `Webpublisher is only compatible with TVPaint version 0.1.0 or earlier.`

**Comment by iLLiCiTiT** [comment]
> Maybe the wording "required" should be slightly different here as this is a warning about compatibility not requirements.

It is about requirement of a compatible version. It means "I don't require tvpaint to run, but if there is tvpaint I need version less than 0.1.0"

**Comment by Innders** [comment]
> It is about requirement of a compatible version. It means "I don't require tvpaint to operate, but if there is tvpaint, I require version less or equal to 0.1.0"

But if it's a requirement then the severity=error.

Severity=warning should be like "It would be great if you had this version as we know it's definitely compatible but it's not required and you can create the bundle anyway but things might break btw".

**Review by Innders — CHANGES_REQUESTED** [review]
Found a bug.

When webpublisher has a required addon the warning message will mention webpublisher not the required addon.

```python
# webpublisher 1.0.8-broken package.py
ayon_required_addons =  {
    "core": ">=0.1.0",
}
```

`[POST] api/bundles/check` request
```js
addons: {
...,
blender: "0.1.6",
core: null,
deadline: "0.1.9",
webpublisher: "1.0.8-broken"
...
}
```
Response

```json
{
    "success": false,
    "issues": [
        {
            "severity": "error",
            "addon": "webpublisher",
            "message": "webpublisher is required"
        },
    ]
}
```

**Comment by Innders** [comment]
Found another bug.

```python
ayon_required_addons =  {
    "core": ">=0.1.0",
    "blender": ">=0.1.1",
    "fusion": None,
}
```

`"fusion": None` seems to break everything, the check will always return `success=true`.

Is it even possible to require to NOT have an addon. 

Maybe `cool-addon` would require that `uncool-addon` is not also installed.

**Comment by Innders** [comment]
Is there some how we can include the required addon in the response?

```
    "issues": [
        {
            "severity": "error",
            "addon": "webpublisher",
            "message": "traypublisher 0.1.2 is required",
            "required": "traypublisher"
        },
    ]
    ```
    
    It would be handy to be able to click on the issue and it scroll you to the addon so you can change the version.

**Pull request merged**
