### PR TITLE
Anatomy: Entity type scoped statuses

### PR DESCRIPTION
**Pull request by martastain**
Exposes "scope" field in project anatomy (list of strings) that allows limiting statuses to certain entity types.

If the field is empty, status will be available for all entities. Otherwise only on specified types (folder / task / product / version / representation / workfile ).

image

This need a counterpart implementation in the frontend (and the launcher)

### CODE REVIEW

**Review by jakubjezek001 — APPROVED** [review]
this is looking good! this will help allign statuses with Flow (SG)

**Review by iLLiCiTiT — APPROVED** [review]
It is ok. This might require minor version bump.

**Comment by mkolar** [comment]
Is anything preventing this from being merged?

**Comment by martastain** [comment]
> Is anything preventing this from being merged?

It is not implemented in the frontend, so changes here won't affect anything yet. But i guess we can merge it and implement the frontend part later.

**Pull request merged**
